font_family JetBrainsMono Nerd Font

background #1a1a1a
foreground #ffffff

background_opacity 0.50
background_blur 1

selection_background #9f4559
selection_foreground #ffffff

cursor #ffffff
cursor_text_color #000000

confirm_os_window_close 0
enable_audio_bell no
window_padding_width 6
