general {
    lock_cmd = hyprlock
    before_sleep_cmd = loginctl lock-session
    after_sleep_cmd = hyprctl dispatch dpms on
}

# screen lock
listener {
    timeout = 300
    on-timeout = hyprlock
}

# screen off
listener {
    timeout = 600
    on-timeout = hyprctl dispatch dpms off
}
