general {
    hide_cursor = false
    immediate_render = false
    screencopy_mode = 0
}

background {
    monitor =
    path = screenshot
    color = rgba(10, 10, 10, 1.0)
    blur_passes = 2
    blur_size = 5
}

input-field {
    monitor =
    size = 280, 56
    outline_thickness = 1
    rounding = -1

    outer_color = rgba(255, 255, 255, 0.22)
    inner_color = rgba(0, 0, 0, 0.35)
    font_color = rgb(255, 255, 255)

    dots_size = 0.22
    dots_spacing = 0.18
    dots_center = true
    fade_on_empty = false
    placeholder_text = <i>Password...</i>

    position = 0, 0
    halign = center
    valign = center
}
